### ISSUE TITLE
Dropping entities does not work on solr

### ISSUE THREAD

**Issue by silvanheller** [vitrivr/ADAMpro#10]
Solr version: 7.5
ADAMpro branch: master
To reproduce: Create an entity with the solr handler, fill it with some data, and then try dropping it
Expected result: Entity is gone / Data is gone
Actual result: Entity is still there with all the data.

Or is it possible that ADAMpro does not remember the old entity name which causes it to just create a new entity with a new random number at the end?

**Comment by ivangiangreco** [comment]
The fact that a new entity name is used on solr, is intended. The name is just used internally. However, there is definitely a problem with dropping entities. 

The error on deletion has been fixed 6f2553f40c1c20f7936dd8bc09b698535d44bdcf.
