### ISSUE TITLE
How does the ADAMpro database client find data

### ISSUE THREAD

**Issue by lxx1220** [vitrivr/ADAMpro#12]
Hello! Is there an instruction manual for the client and its use? Thank you.

**Comment by lucaro** [comment]
Hey, I'm not sure I understand what you are asking. Does this guide contain the information you are looking for? https://vitrivr.org/getting_started.html

**Comment by lxx1220** [comment]
Hi,  what is the relationship between Cineast and ADAMpro?  If I add the index given in this article to the ADAMpro client,  what happens when I look up the image?  Will it affect my query?   The graph of my dataset. Thanks!

**Comment by lucaro** [comment]
ADAMpro and Cineast work together to answer similarity queries, maybe have a look at https://vitrivr.org/vitrivr.html or https://sigmm.hosting.acm.org/?open-source-item=content-based-multimedia-retrieval-using-vitrivr for an overview of the vitrivr stack.

By the ADAMpro client, you mean the web interface on port 9099?

Adding an index can increase query performance, depending on the size of the dataset you want to search and the type of feature and index you are using. Search does work without any index structures, it might just be slower.

**Comment by lxx1220** [comment]
the ADAMpro client is the web interface on port 9099. 
I added index structure in port 9090 and query on cineast. Has its similarity improved?
 Is the query result set on port 9090 consistent with the result on cineast? 
In the 9090 port query result set, I have about 1000 images in my data set, and I have used LSH index structure, and I have waited for more than an hour without executing results? How long will it take? 
Besides, I use a notebook.
Thanks！

**Comment by lucaro** [comment]
I'm not sure I understand what you are trying to do. Have you set up the rest of the vitrivr stack as well? Which features did you extract and how many images are in your dataset in total? The index structures do not improve the similarity, but they potentially decrease the query time.

**Comment by lxx1220** [comment]
The rest are also installed. There are 1000 images in the data set, and the extracted features are image features. I want to know the image database of your proposed system. Thank you!

**Comment by lucaro** [comment]
Did you extract the image features using Cineast as described in https://vitrivr.org/getting_started.html#running-the-extraction ? Are you able to retrieve anything using the vitrivr-ng interface?
