### ISSUE TITLE
SLF4J marked as provided dependency

### ISSUE THREAD

**Issue by silvanheller** [vitrivr/ADAMpro#5]
My IntelliJ thinks org.slf4j:slf4j-api:1.7.22 as a provided dependency and therefore doesn't compile. slf4j-api:1.7.10 is a runtime dependency according to the SBT tool (see screenshot)
![image](https://user-images.githubusercontent.com/14314470/35338966-8ee93d5e-011f-11e8-83b8-1571995f9419.png)

**Comment by ivangiangreco** [comment]
Explained and adjusted in Documentation.
