### ISSUE TITLE
Git clone requires to download submodules

### ISSUE THREAD

**Issue by awani216** [vitrivr/ADAMpro#6]
For natively deploying ADAMpro we need to clone submodule gprc. I think it will be helpful if it is explicitly mentioned in the wiki page deployment.
This should also be reflected in native deployment section of getting started page https://vitrivr.org/getting_started.html
Should I submit a PR for this?

**Comment by silvanheller** [comment]
Thanks for mentioning it! While it's noted in the [Dev Section](https://github.com/vitrivr/ADAMpro/wiki/Development-and-Configuration) of  the wiki, it's indeed not yet in the readme / getting started of the website.
@ivangiangreco will fix this on the website soon :tm:

**Comment by awani216** [comment]
I would  Like to update it on readme as well as native deployment on the wiki page.
Should I  submit a PR for this?

**Comment by silvanheller** [comment]
Sure, go ahead with a suggestion and we'll take a look at it.

**Comment by ivangiangreco** [comment]
Thank you for the comments. I have updated the vitrivr website and the wiki.
