### ISSUE TITLE
Exclude log4j.properties in SBT

### ISSUE THREAD

**Issue by silvanheller** [vitrivr/ADAMpro#8]
Logging is currently broken in the docker-container as a log4j.properties file. The preferred fix is to exclude the log4j.properties file, alternatively you could just switch to .properties from .xml

**Comment by silvanheller** [comment]
Not fixed for the latest selfcontained Dockercontainer

**Comment by ivangiangreco** [comment]
The problem is the verbose logging of Cassandra, not of any ADAMpro related code.  It should be fixed with 47ad00b109c11cd8271ba5555cc9e66f653e95c3 .
